In [1]:
###################################
# Volume du cône
# ex 1
###################################

# définition des variables
rayon = 5.2
hauteur = 14.3
pi = 3.14

# formule du volume avec approximation de pi
volume1 = (1/3)* pi * rayon**2 * hauteur

# formule du volume avec la variable pi de la lib math
import math
volume2 = (1/3)* math.pi * rayon**2 * hauteur

# la difference observee
dV = abs(volume2-volume1)

print("avec approximation, volume = ", volume1)
print("avec math.pi, volume = ", volume2)
print("soit une différence de ",dV)


avec approximation, volume =  404.7166933333334
avec math.pi, volume =  404.92197151629085
soit une différence de  0.20527818295744282


In [2]:
###################################
# tests logiques
# ex 2
###################################
A= 5.2
B = 4.7

print("A supérieur à B? ", A>B)
print("A égal à B? ", A==B)

PEA = int(A)  # partie entiere de A
PDB = B-int(B) # partie décimale de B
print(PDB<PEA)


A supérieur à B?  True
A égal à B?  False
True


In [3]:
###################################
# listes 
# ex 3
###################################

liste = [1,10,4,50,4,37,2,4]
liste.append(4)
print(dir(liste))
liste.sort()
print(liste)
print(liste.count(4))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
[1, 2, 4, 4, 4, 4, 10, 37, 50]
4


In [4]:
###################################
# Numpy arrays
# ex 4
###################################
import numpy as np
A = np.full((5,5), 7)
B = np.ones((5,3))
C = np.identity(5)

#1/
C = 5*C
print("C = ")
print(C)

#2/
D = A.dot(C)
print("D = ")
print(D)

#3/
E = D[:,4] + B[:,1]
print("E = ")
print(E)

#4/
print("mean D: ", D.mean(0))

#5/
print("mean E: ", E.mean())


C = 
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
D = 
[[35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]]
E = 
[36. 36. 36. 36. 36.]
mean D:  [35. 35. 35. 35. 35.]
mean E:  36.0


In [5]:
###################################
# Numpy arrays
# ex 5
###################################
import pandas as pd
data = pd.read_csv("https://github.com/dbendet/coursera_machine_learning/raw/master/kc_house_data.csv")
print(data)
print()
data = data.to_numpy() # on transforme l'objet dataframe en array numpy

#### combien de lignes et colonnes
dimensions = data.shape
print(type(dimensions))
nbl = dimensions[0] # nombre de lignes
nbc = dimensions[1] # nombre de colonnes

print("lignes = ",nbl)
print("colonnes = ",nbc)
print()

#### Calcul du Z-score du prix (3e colonne=>indice 2)
priceMean = data[:,2].mean()  #valeur mean des prix
priceStd  = data[:,2].std()   #stdandard deviation des prix
priceZScore = (data[:,2]-priceMean)/priceStd
print("Z-score :")
print(priceZScore)
print()


#### outlier
# on fait un sort des valeurs pour identifier les valeurs correspondant aux 2% des valeurs extrêmes
priceCol = data[:,2].copy()
priceColSorted = priceCol.copy()
priceColSorted.sort()
val5percentMin = priceColSorted[int(nbl*0.02)]
val5percentMax = priceColSorted[int(nbl*0.98)]
#toutes les valeurs qui ne sont pas des outliers sont comprises entre val5percentMin et val5percentMax
np.bincount(np.greater(priceCol,val5percentMin) &  np.less(priceCol,val5percentMax))  #false est vu comme 0, true comme 1



               id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242   

array([  882, 20731], dtype=int64)

In [6]:
###################################
# conditionelle
# ex 6
###################################
A = 5
B = 7
if(A>B):
    print("A superieur")
else:
    print("B superieur")
    

A = np.full((3,3),5)
A[0,0] = 30
B = np.full((3,3),7)
B[0,0] = -4
#solution pas élégante
C = np.empty((3,1))
if(A[0,:].mean()>B[0,:].mean()):
    C[0] = A[0,:].mean()
else:
    C[0] = B[0,:].mean()
    
if(A[1,:].mean()>B[1,:].mean()):
    C[1] = A[1,:].mean()
else:
    C[1] = B[1,:].mean()
    
if(A[2,:].mean()>B[2,:].mean()):
    C[2] = A[2,:].mean()
else:
    C[2] = B[2,:].mean()
print(C)

#solution plus élégante
np.maximum(A.mean(1),B.mean(1))

B superieur
[[13.33333333]
 [ 7.        ]
 [ 7.        ]]


array([13.33333333,  7.        ,  7.        ])

In [7]:
###################################
# boucles
# ex 8
###################################
#1/ table de multiplication de 7
for i in np.arange(0,10):
    print("7x",i,"=",7*i)

#2/ table de multiplication de 1 à 9
for j in np.arange(1,10):
    for i in np.arange(0,10):
        #print(j,"x",i,"=",j*i)
        i*j

        
#3/
tableau = np.empty((24,12))
for line in np.arange(0,24):
    for column in np.arange(0,12):
        if(line>column):
            tableau[line,column] = 5
        else:
            tableau[line,column] = 10

for line in np.arange(0,24):
    for column in np.arange(0,12):
        if(tableau[line,column]>i):
            value_tmp = 0
            
            for column2 in np.arange(0,j):
                value_tmp = value_tmp+tableau[i,j]
            tableau[line,column] = value_tmp
        
        else:
            tableau[line,column] = np.log(tableau[line,column])
            
print(tableau)

7x 0 = 0
7x 1 = 7
7x 2 = 14
7x 3 = 21
7x 4 = 28
7x 5 = 35
7x 6 = 42
7x 7 = 49
7x 8 = 56
7x 9 = 63
[[ 90.          90.          90.          90.          90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791  90.          90.          90.          90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791   1.60943791  90.          90.          90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791   1.60943791   1.60943791  90.          90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791   1.60943791   1.60943791   1.60943791  90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791   1.60943791   1.60943791   1.60943791   1.60943791
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.609437

In [8]:
###################################
# boucles + dict + numpy
# ex 9
###################################

import pandas as pd
data = pd.read_csv("https://github.com/dbendet/coursera_machine_learning/raw/master/kc_house_data.csv")
print(data)
data = data.to_numpy()

def Score(price, surface):
    score = price/surface
    return score


# score max
numberOfLines = data.shape[0]
line = 0
result = {}

while(line<numberOfLines):
    numberOfRooms = data[line,3] + data[line,4]
    score_current = Score(data[line,2],data[line,5])
    if(numberOfRooms in result):
        if(result[numberOfRooms]<score_current):
            result[numberOfRooms]=score_current
    else:
        result[numberOfRooms]=score_current
    line = line+1

print(result)





               id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242   

In [9]:
###################################
# Pandas
# ex 10
###################################

In [17]:
import pandas as pd
import numpy as np
data = pd.read_csv("https://github.com/dbendet/coursera_machine_learning/raw/master/kc_house_data.csv")



data['price2'] = data['price']*0.8
data

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  sqft_above  \
0             1180      5650     1.0           0     0  ...        1180   
1             2570      7242     2.0           0     0  ...        2170   
2              770     10000     1.0           0     0  ...         770   
3             1960      5000     1.0           0     0  ...        1050   
4             1680      8080     1.0           0     0  ...        1680   
...            ...       ...     ...         ...   ...  ...         ...   
21608         1530      1131     3.0           0     0  ...        1530   
21609         2310      5813     2.0           0     0  ...        2310   
21610         1020      1350     2.0           0     0  ...        1020   
21611         1600      2388     2.0           0     0  ...        1600   
21612         1020      1076     2.0           0     0  ...        1020   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0                  0      1955             0    98178  47.5112 -122.257   
1                400      1951          1991    98125  47.7210 -122.319   
2                  0      1933             0    98028  47.7379 -122.233   
3                910      1965             0    98136  47.5208 -122.393   
4                  0      1987             0    98074  47.6168 -122.045   
...              ...       ...           ...      ...      ...      ...   
21608              0      2009             0    98103  47.6993 -122.346   
21609              0      2014             0    98146  47.5107 -122.362   
21610              0      2009             0    98144  47.5944 -122.299   
21611              0      2004             0    98027  47.5345 -122.069   
21612              0      2008             0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15    price2  
0               1340        5650  177520.0  
1               1690        7639  430400.0  
2               2720        8062  144000.0  
3               1360        5000  483200.0  
4               1800        7503  408000.0  
...              ...         ...       ...  
21608           1530        1509  288000.0  
21609           1830        7200  320000.0  
21610           1020        2007  321680.8  
21611           1410        1287  320000.0  
21612           1020        1357  260000.0  

[21613 rows x 22 columns]

In [22]:
data.loc[(data['bedrooms']>2),['price2']] = data.loc[(data['bedrooms']>2),['price2']]+300
data.loc[(data['bedrooms']>2),['price2']]

price2
0      177820.0
1      430700.0
3      483500.0
4      408300.0
5      980300.0
...         ...
21606  806300.0
21607  380300.0
21608  288300.0
21609  320300.0
21611  320300.0

[18641 rows x 1 columns]

In [23]:
data.loc[(data['bedrooms']>2)&(data['bathrooms']>2),['price2']] = data.loc[(data['bedrooms']>2),['price2']]+500
data.loc[(data['bedrooms']>2),['price2']]

price2
0      177820.0
1      431200.0
3      484000.0
4      408300.0
5      980800.0
...         ...
21606  806800.0
21607  380800.0
21608  288800.0
21609  320800.0
21611  320800.0

[18641 rows x 1 columns]

In [25]:
data.mean()

id               4.580302e+09
price            5.400881e+05
bedrooms         3.370842e+00
bathrooms        2.114757e+00
sqft_living      2.079900e+03
sqft_lot         1.510697e+04
floors           1.494309e+00
waterfront       7.541757e-03
view             2.343034e-01
condition        3.409430e+00
grade            7.656873e+00
sqft_above       1.788391e+03
sqft_basement    2.915090e+02
yr_built         1.971005e+03
yr_renovated     8.440226e+01
zipcode          9.807794e+04
lat              4.756005e+01
long            -1.222139e+02
sqft_living15    1.986552e+03
sqft_lot15       1.276846e+04
price2           4.325809e+05
dtype: float64

In [26]:
data.median()

id               3.904930e+09
price            4.500000e+05
bedrooms         3.000000e+00
bathrooms        2.250000e+00
sqft_living      1.910000e+03
sqft_lot         7.618000e+03
floors           1.500000e+00
waterfront       0.000000e+00
view             0.000000e+00
condition        3.000000e+00
grade            7.000000e+00
sqft_above       1.560000e+03
sqft_basement    0.000000e+00
yr_built         1.975000e+03
yr_renovated     0.000000e+00
zipcode          9.806500e+04
lat              4.757180e+01
long            -1.222300e+02
sqft_living15    1.840000e+03
sqft_lot15       7.620000e+03
price2           3.608000e+05
dtype: float64

In [27]:
data.sum()

id                                                  98994056770455
date             20141013T00000020141209T00000020150225T0000002...
price                                                  1.16729e+10
bedrooms                                                     72854
bathrooms                                                  45706.2
sqft_living                                               44952873
sqft_lot                                                 326506890
floors                                                     32296.5
waterfront                                                     163
view                                                          5064
condition                                                    73688
grade                                                       165488
sqft_above                                                38652488
sqft_basement                                              6300385
yr_built                                                  4259

In [29]:
Zscore = (data['price']-data['price'].mean())/data['price'].std()
Zscore

0       -0.866697
1       -0.005688
2       -0.980827
3        0.174086
4       -0.081956
           ...   
21608   -0.490533
21609   -0.381579
21610   -0.375856
21611   -0.381579
21612   -0.585868
Name: price, Length: 21613, dtype: float64