In [1]:
###################################
# Volume du cône
# ex 1
###################################

# définition des variables
rayon = 5.2
hauteur = 14.3
pi = 3.14

# formule du volume avec approximation de pi
volume1 = (1/3)* pi * rayon**2 * hauteur

# formule du volume avec la variable pi de la lib math
import math
volume2 = (1/3)* math.pi * rayon**2 * hauteur

# la difference observee
dV = abs(volume2-volume1)

print("avec approximation, volume = ", volume1)
print("avec math.pi, volume = ", volume2)
print("soit une différence de ",dV)


avec approximation, volume =  404.7166933333334
avec math.pi, volume =  404.92197151629085
soit une différence de  0.20527818295744282


In [2]:
###################################
# tests logiques
# ex 2
###################################
A= 5.2
B = 4.7

print("A supérieur à B? ", A>B)
print("A égal à B? ", A==B)

PEA = int(A)  # partie entiere de A
PDB = B-int(B) # partie décimale de B
print(PDB<PEA)


A supérieur à B?  True
A égal à B?  False
True


In [6]:
###################################
# listes 
# ex 3
###################################

liste = [1,10,4,50,4,37,2,4]
liste.append(4)
print(dir(liste))
liste.sort()
print(liste)
print(liste.count(4))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
[1, 2, 4, 4, 4, 4, 10, 37, 50]
4


In [27]:
###################################
# Numpy arrays
# ex 4
###################################
import numpy as np
A = np.full((5,5), 7)
B = np.ones((5,3))
C = np.identity(5)

#1/
C = 5*C
print("C = ")
print(C)

#2/
D = A.dot(C)
print("D = ")
print(D)

#3/
E = D[:,4] + B[:,1]
print("E = ")
print(E)

#4/
print("mean D: ", D.mean(0))

#5/
print("mean E: ", E.mean())


C = 
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
D = 
[[35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]]
E = 
[36. 36. 36. 36. 36.]
mean D:  [35. 35. 35. 35. 35.]
mean E:  36.0


In [40]:
###################################
# Numpy arrays
# ex 5
###################################
import pandas as pd
data = pd.read_csv("https://github.com/dbendet/coursera_machine_learning/raw/master/kc_house_data.csv")
print(data)
print()
data = data.to_numpy() # on transforme l'objet dataframe en array numpy

#### combien de lignes et colonnes
dimensions = data.shape
print(type(dimensions))
nbl = dimensions[0] # nombre de lignes
nbc = dimensions[1] # nombre de colonnes

print("lignes = ",nbl)
print("colonnes = ",nbc)
print()

#### Calcul du Z-score du prix (3e colonne=>indice 2)
priceMean = data[:,2].mean()  #valeur mean des prix
priceStd  = data[:,2].std()   #stdandard deviation des prix
priceZScore = (data[:,2]-priceMean)/priceStd
print("Z-score :")
print(priceZScore)
print()


#### outlier
# on fait un sort des valeurs pour identifier les valeurs correspondant aux 2% des valeurs extrêmes
priceCol = data[:,2].copy()
priceColSorted = priceCol.copy()
priceColSorted.sort()
val5percentMin = priceColSorted[int(nbl*0.02)]
val5percentMax = priceColSorted[int(nbl*0.98)]
#toutes les valeurs qui ne sont pas des outliers sont comprises entre val5percentMin et val5percentMax
np.bincount(np.greater(priceCol,val5percentMin) &  np.less(priceCol,val5percentMax))  #false est vu comme 0, true comme 1



               id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242   

array([  882, 20731], dtype=int64)

In [50]:
###################################
# conditionelle
# ex 6
###################################
A = 5
B = 7
if(A>B):
    print("A superieur")
else:
    print("B superieur")
    

A = np.full((3,3),5)
A[0,0] = 30
B = np.full((3,3),7)
B[0,0] = -4
#solution pas élégante
C = np.empty((3,1))
if(A[0,:].mean()>B[0,:].mean()):
    C[0] = A[0,:].mean()
else:
    C[0] = B[0,:].mean()
    
if(A[1,:].mean()>B[1,:].mean()):
    C[1] = A[1,:].mean()
else:
    C[1] = B[1,:].mean()
    
if(A[2,:].mean()>B[2,:].mean()):
    C[2] = A[2,:].mean()
else:
    C[2] = B[2,:].mean()
print(C)

#solution plus élégante
np.maximum(A.mean(1),B.mean(1))

B superieur
[[13.33333333]
 [ 7.        ]
 [ 7.        ]]


array([13.33333333,  7.        ,  7.        ])

In [63]:
###################################
# boucles
# ex 8
###################################
#1/ table de multiplication de 7
for i in np.arange(0,10):
    print("7x",i,"=",7*i)

#2/ table de multiplication de 1 à 9
for j in np.arange(1,10):
    for i in np.arange(0,10):
        #print(j,"x",i,"=",j*i)
        i*j

        
#3/
tableau = np.empty((24,12))
for line in np.arange(0,24):
    for column in np.arange(0,12):
        if(line>column):
            tableau[line,column] = 5
        else:
            tableau[line,column] = 10

for line in np.arange(0,24):
    for column in np.arange(0,12):
        if(tableau[line,column]>i):
            value_tmp = 0
            
            for column2 in np.arange(0,j):
                value_tmp = value_tmp+tableau[i,j]
            tableau[line,column] = value_tmp
        
        else:
            tableau[line,column] = np.log(tableau[line,column])
            
print(tableau)

7x 0 = 0
7x 1 = 7
7x 2 = 14
7x 3 = 21
7x 4 = 28
7x 5 = 35
7x 6 = 42
7x 7 = 49
7x 8 = 56
7x 9 = 63
[[ 90.          90.          90.          90.          90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791  90.          90.          90.          90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791   1.60943791  90.          90.          90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791   1.60943791   1.60943791  90.          90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791   1.60943791   1.60943791   1.60943791  90.
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.60943791   1.60943791   1.60943791   1.60943791   1.60943791
   90.          90.          90.          90.          90.
   90.          90.        ]
 [  1.609437

In [70]:
###################################
# boucles + dict + numpy
# ex 9
###################################

import pandas as pd
data = pd.read_csv("https://github.com/dbendet/coursera_machine_learning/raw/master/kc_house_data.csv")
print(data)
data = data.to_numpy()

def Score(price, surface):
    score = price/surface
    return score


# score max
numberOfLines = data.shape[0]
line = 0
result = {}

while(line<numberOfLines):
    numberOfRooms = data[line,3] + data[line,4]
    score_current = Score(data[line,2],data[line,5])
    if(numberOfRooms in result):
        if(result[numberOfRooms]<score_current):
            result[numberOfRooms]=score_current
    else:
        result[numberOfRooms]=score_current
    line = line+1

print(result)





               id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242   